# dolt-service.yaml
# Exposes the Dolt SQL server within the cluster.
# Other pods (including Signadot Resource Plugin runners) access Dolt 
# via the DNS name: dolt-db.hotrod.svc

apiVersion: v1
kind: Service
metadata:
  name: dolt-db
  namespace: hotrod
  labels:
    app: dolt-db
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: dolt-db
