apiVersion: v1
kind: Secret
metadata:
  name: users-db-credentials
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_kWDBp9eLu6nP@ep-hidden-resonance-aegr35t7.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require"