apiVersion: v1
kind: Secret
metadata:
  name: users-db-credentials
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_w96GqDPdoVCc@ep-ancient-sunset-ahaw7ysn-pooler.c-3.us-east-1.aws.neon.tech/appdb?sslmode=require&channel_binding=require"
